### ISSUE TITLE
Request to add AWS .NET Distributed Cache Provider to NuGet

### ISSUE THREAD

**Issue by leevg** [awslabs/aws-dotnet-distributed-cache-provider#32]
Hi. Would it be possible to add AWS .NET Distributed Cache Provider to NuGet?

**Comment by normj** [comment]
Hi @leevg. We plan to publish this library to NuGet. We are finishing up the internal review (i.e. legal and such) then we can publish.

**Comment by leevg** [comment]
Hi @normj. Any updates?

**Comment by normj** [comment]
Unfortunately no updates right now. We are waiting our turn for the AppSec review.

**Comment by ashovlin** [comment]
We've finished all of the internal launch preparation, and just pushed the initial preview version to https://www.nuget.org/packages/AWS.AspNetCore.DistributedCacheProvider/.

Here's the launch blog post with some more examples: https://aws.amazon.com/blogs/developer/introducing-the-aws-net-distributed-cache-provider-for-dynamodb-preview/

Let us know what you think via issues and/or pull requests!

**Comment by rajeshaz09** [comment]
1 year back i implemented dynamodb distributed cache for asp.net ccre in one of the project. We faced similar issue. I followed below logic

Use [messagepack for c#](https://github.com/MessagePack-CSharp/MessagePack-CSharp) to compress data in efficient way

Split message into multiple based on max dynamodb size then introduced sort key as message number

When reading... get all items with partition key then merge data as per sort key 

Below optional optimisation i did

During writing make sure you delete items with sortkey greater than message split count. In rare cases we may face this problem. Initially there might be N split messages, but when you update cache, you may set value to much lesser data which may endup less than N messages.
